spring:
  application:
    name: fire-extinguisher-selling
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fire_extinguisher_selling?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

server:
  port: 8080

fire-extinguisher-selling:
  checkKey: 123456

wechat:
  # 小程序 appid
  appid:
  # 小程序密钥
  secret:
  # 默认头像（所有微信用户统一使用）
  default-avatar:

order:
  worker-id: 01